GHOST-493: [stage2] Avoid infinite loop when retrieving tags  and enhance errors handling

diff --git a/scripts/stage2 b/scripts/stage2
--- a/scripts/stage2
+++ b/scripts/stage2
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -x
+set -xu
 
 LOCK=/run/lock/ghost-stage-2
 AWS_BIN=$(which aws)
@@ -27,22 +27,32 @@ COLOR_RED='\033[00;31m'
 COLOR_GREEN='\033[00;32m'
 COLOR_YELLOW='\033[00;33m'
 
+set -e
+trap exit_deployment EXIT
+
 INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
 EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
 EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
 
+retry=0
 while [ -z "$APP" ] || [ -z "$ENV" ] || [ -z "$ROLE" ] ; do
-  # TODO: Exit with error after N retry
-  echo "Waiting 1s for (app, env, role) tags to be set..."
-  sleep 1
+    echo "Waiting 2s for (app, env, role) tags to be set..."
+    sleep 2
 
-  TAGS=$($AWS_BIN ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" --region "$EC2_REGION")
+    TAGS=$($AWS_BIN ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" --region "$EC2_REGION")
 
-  NAME=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["Name"] | select (.!=null)')
-  APP=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["app"] | select (.!=null)')
-  ENV=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["env"] | select (.!=null)')
-  ROLE=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["role"] | select (.!=null)')
-  COLOR=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["color"] | select (.!=null)')
+    NAME=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["Name"] | select (.!=null)')
+    APP=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["app"] | select (.!=null)')
+    ENV=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["env"] | select (.!=null)')
+    ROLE=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["role"] | select (.!=null)')
+    COLOR=$(echo $TAGS | jq -r ".Tags[] | { key: .Key, value: .Value } | [.] | from_entries" | jq -r '.["color"] | select (.!=null)')
+
+    ((retry++))
+    if [ $retry -gt 150 ] ; then
+        # After 5min, no more hope for tags...
+        echo "[ERROR] Cannot retrieve instance tags, exiting."
+        exit_deployment -1
+    fi
 done
 
 if [ ! -d /ghost ]; then
@@ -50,11 +60,11 @@ if [ ! -d /ghost ]; then
 fi
 
 if [ ! -d /var/lib/ghost ]; then
-    mkdir /var/lib/ghost
+    mkdir -p /var/lib/ghost
 fi
 
 if [ ! -d ${LOGDIR} ]; then
-    mkdir ${LOGDIR}
+    mkdir -p ${LOGDIR}
 fi
 
 if [ ! -z "$COLOR" ]; then
@@ -64,6 +74,8 @@ else
 fi
 
 IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+
+set +e
 
 function zabbix_hostname() {
     # Update Zabbix agent Hostname
