GHOST-127: Variable checks to avoid bad remove

diff --git a/scripts/stage2 b/scripts/stage2
--- a/scripts/stage2
+++ b/scripts/stage2
@@ -88,6 +88,11 @@ function deploy_module() {
     MODULE_NAME=$1
     MODULE_FILE=$2
     TARGET=$3
+    if [ ${TARGET%%+(/)} == "/tmp" ]; then
+        echo "Target path cannot be /tmp"
+        exit_deployment -1
+    fi
+
     echo "--------------------------------" >> /tmp/$LOGFILE
     echo "Deploying module $MODULE_NAME in $TARGET" >> /tmp/$LOGFILE
     /usr/local/bin/aws s3 cp s3://$S3_BUCKET/ghost/$APP/$ENV/$ROLE/$MODULE_NAME/$MODULE_FILE /tmp/$MODULE_FILE  --region "$EC2_REGION"
@@ -96,11 +101,15 @@ function deploy_module() {
     chown -R admin:admin /ghost/$UUID
     echo "Extracting module in /ghost/$UUID" >> /tmp/$LOGFILE
     tar xvzf /tmp/$MODULE_FILE -C /ghost/$UUID > /dev/null
+    if [ $? -ne 0 ] || [ ! -f /tmp/$MODULE_FILE ]; then
+        echo "Extracting module failed !"
+        exit_deployment -1
+    fi
+
     rm -rf /tmp/$MODULE_FILE
     cd /ghost/$UUID
 
-    if [ -e predeploy ]
-    then
+    if [ -e predeploy ]; then
         echo "Executing predeploy script..." >> /tmp/$LOGFILE
         chmod +x predeploy
         GHOST_APP=$APP GHOST_ENV=$ENV GHOST_ROLE=$ROLE GHOST_MODULE_NAME=$MODULE_NAME GHOST_MODULE_PATH=$TARGET ./predeploy 2>&1 | tee -a /tmp/$LOGFILE
@@ -112,8 +121,7 @@ function deploy_module() {
     fi
 
     # Clear folder if not a symlink (not a Ghost managed module)
-    if ! [ -h $TARGET ]
-    then
+    if ! [ -h $TARGET ]; then
         echo "Clearing unmanaged folder..." >> /tmp/$LOGFILE
         rm -rfv $TARGET
     fi
@@ -122,8 +130,7 @@ function deploy_module() {
     ln -fsn /ghost/$UUID $TARGET
     cd $TARGET
 
-    if [ -e postdeploy ]
-    then
+    if [ -e postdeploy ]; then
         echo "Executing postdeploy script..." >> /tmp/$LOGFILE
         chmod +x postdeploy
         GHOST_APP=$APP GHOST_ENV=$ENV GHOST_ROLE=$ROLE GHOST_MODULE_NAME=$MODULE_NAME GHOST_MODULE_PATH=$TARGET ./postdeploy 2>&1 | tee -a /tmp/$LOGFILE
@@ -138,7 +145,7 @@ function find_module() {
         MODULE_NAME=$(echo $line | awk -F':' '{print $1}')
         MODULE_FILE=$(echo $line | awk -F':' '{print $2}')
         TARGET=$(echo $line | awk -F':' '{print $3}')
-	    if [ "$1" == "$MODULE_NAME" ]; then
+        if [ "$1" == "$MODULE_NAME" ]; then
             echo $MODULE_NAME $MODULE_FILE $TARGET
         fi
     done
