GHOST-481: More generic status notifier

diff --git a/scripts/stage2 b/scripts/stage2
--- a/scripts/stage2
+++ b/scripts/stage2
@@ -33,10 +33,8 @@ function exit_deployment() {
     echo "Unlocking $LOCK..."
     rmdir $LOCK
     echo "Unlocked $LOCK"
-    BOOTSTRAP_PAYLOAD="{\"status\":\"${1}\",\"hostname\":\"${EC2_HOSTNAME}\"}"
-    echo "Posting payload $BOOTSTRAP_PAYLOAD to $BOOTSTRAP_ENDPOINT" >> /var/log/ghost/$LOGFILE
-    curl -H "Content-Type: application/json" -X POST -d $BOOTSTRAP_PAYLOAD $BOOTSTRAP_ENDPOINT
     trap - EXIT
+    notify_status $1
     if [ -z $1 ]; then
         exit -1
     else
@@ -97,6 +95,17 @@ fi
 IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
 MAX_NAME=$(($(getconf HOST_NAME_MAX)-16))
 EC2_HOSTNAME=$(echo ${NAME:0:$MAX_NAME}-${IP} | tr -s '.' '-')
+
+function notify_status() {
+    if [[ $1 =~ ^-?[0-9]+$ ]]; then
+        status=$([ "$1" == 0 ] && echo "done" || echo "failed")
+        bootstrap_payload=$(printf '{"status":"%s","return_code":"%s","hostname":"%s"}' "$status" "$1" "$EC2_HOSTNAME")
+    else
+        bootstrap_payload=$(printf '{"status":"%s","hostname":"%s"}' "$1" "$EC2_HOSTNAME")
+    fi
+    echo "Posting payload $bootstrap_payload to $BOOTSTRAP_ENDPOINT" >> /var/log/ghost/$LOGFILE
+    curl -H "Content-Type: application/json" -X POST -d $bootstrap_payload $BOOTSTRAP_ENDPOINT
+}
 
 set +e
 
@@ -284,6 +293,8 @@ function download_and_run_lifecycle_hook_script() {
     fi
 }
 
+notify_status 'init'
+
 echo "Downloading Manifest" >> $LOGFILE
 $AWS_BIN s3 cp --only-show-errors s3://${S3_BUCKET}/${APP_PATH}/MANIFEST /tmp/ --region "$S3_REGION"
 
@@ -292,6 +303,8 @@ if [ $? -ne 0 ]; then
     # init zabbix before quit
     exit_deployment -3
 fi
+
+notify_status 'started'
 
 if [ -n "$1" ]; then
     # Deploy only one module
